import styled from 'styled-components';
import MEDIA from 'helpers/mediaTemplates';

export const GameStatus = styled.div`
  font-size: 3.8rem;
  margin: 2rem auto 1rem;
  width: 80%;
  max-width: 500px;
  margin: 4rem auto;
  padding: 0.8em;
  background-color: #f2c300;
  color: #000;
  box-shadow: 1px 1px 9px 2px rgba(0, 0, 0, 0.5);

  h2 {
    font-size: 120%;
    font-weight: 600;
    margin: 0 0 2rem;
  }

  p {
    font-weight: 300;
    line-height: 1.2;
  }

  strong {
    font-weight: 600;
  }

  button {
    font-family: Rambla, sans-serif;
    background-color: rgba(0, 184, 68, 1);
    color: #fff;
    border: none;
    border-radius: 0.4em;
    box-shadow: 2px 2px 3px 1px rgba(0, 0, 0, 0.5);
    font-size: 2rem;
    padding: 0.5em 0.8em;
    margin: 1.6em auto 0;
    display: block;
    cursor: pointer;
  }

  button:hover {
    background-color: rgba(0, 164, 48, 1);
  }

  // Star Trek color palette
  // https://www.color-hex.com/color-palette/6450
  // Red: #df0000	(223,0,0)
  // Gold: #f2c300	(242,195,0)
  // Blue: #0099f6	(0,153,246)
  // Green: #00b844	(0, 184, 68)
  // Black: #000000	(0,0,0)

  &.slit-in-vertical {
    -webkit-animation: slit-in-vertical 0.45s ease-out both;
    animation: slit-in-vertical 0.45s ease-out both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2019-9-18 14:43:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slit-in-vertical
 * ----------------------------------------
 */
  @-webkit-keyframes slit-in-vertical {
    0% {
      // -webkit-transform: translateZ(-800px) rotateY(90deg);
      // transform: translateZ(-800px) rotateY(90deg);
      opacity: 0;
      -webkit-filter: blur(90px);
    }
    54% {
      // -webkit-transform: translateZ(-160px) rotateY(87deg);
      // transform: translateZ(-160px) rotateY(87deg);
      opacity: 1;
      -webkit-filter: blur(70px);
    }
    100% {
      // -webkit-transform: translateZ(0) rotateY(0);
      // transform: translateZ(0) rotateY(0);
      -webkit-filter: blur(0);
    }
  }
  @keyframes slit-in-vertical {
    0% {
      // -webkit-transform: translateZ(-800px) rotateY(90deg);
      // transform: translateZ(-800px) rotateY(90deg);
      opacity: 0;
      filter: blur(90px);
    }
    54% {
      // -webkit-transform: translateZ(-160px) rotateY(87deg);
      // transform: translateZ(-160px) rotateY(87deg);
      opacity: 1;
      filter: blur(70px);
    }
    100% {
      // -webkit-transform: translateZ(0) rotateY(0);
      // transform: translateZ(0) rotateY(0);
      filter: blur(0);
    }
  }
`;

export const Buttons = styled.div`
  &.slit-in-vertical {
    -webkit-animation: slit-in-vertical 0.45s ease-in reverse both;
    animation: slit-in-vertical 0.45s ease-in reverse both;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2019-9-18 15:49:7
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation slit-in-vertical
  * ----------------------------------------
  */
  @-webkit-keyframes slit-in-vertical {
    0% {
      -webkit-transform: translateZ(-800px) rotateY(90deg);
      transform: translateZ(-800px) rotateY(90deg);
      opacity: 0;
    }
    54% {
      -webkit-transform: translateZ(-160px) rotateY(87deg);
      transform: translateZ(-160px) rotateY(87deg);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateZ(0) rotateY(0);
      transform: translateZ(0) rotateY(0);
    }
  }
  @keyframes slit-in-vertical {
    0% {
      -webkit-transform: translateZ(-800px) rotateY(90deg);
      transform: translateZ(-800px) rotateY(90deg);
      opacity: 0;
    }
    54% {
      -webkit-transform: translateZ(-160px) rotateY(87deg);
      transform: translateZ(-160px) rotateY(87deg);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateZ(0) rotateY(0);
      transform: translateZ(0) rotateY(0);
    }
  }
`;

export const Container = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-gap: 4rem;
  padding: 0 4rem;
  margin: 2rem 0;

  ${MEDIA.TABLET`
    display: block;
  `};
`;
